/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Deliquescence.Config;
import Deliquescence.Refreshable;

/**
 *
 * @author Josh
 */
public class GameSlidersPanel extends javax.swing.JPanel implements Refreshable {

    /**
     * Creates new form GameSlidersPanel
     */
    public GameSlidersPanel() {
        initComponents();
        Config.refreshables.add(this);
        refreshConfig();
    }

    @Override
    public void refreshConfig() {
        try {//NPE glitch when editing game setup panel
            RowsSlider.setMaximum(Config.getInt("MAX_ROWS"));
            ColumnsSlider.setMaximum(Config.getInt("MAX_COLUMNS"));
            PlayersSlider.setMaximum(Config.getInt("MAX_PLAYERS"));
        } catch (NullPointerException e) {//Config not loaded
            RowsSlider.setMaximum(15);
            ColumnsSlider.setMaximum(10);
            PlayersSlider.setMaximum(8);
        }
    }

    public int getRows() {
        return RowsSlider.getValue();
    }

    public int getColumns() {
        return ColumnsSlider.getValue();
    }

    public int getPlayers() {
        return PlayersSlider.getValue();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayersLabel = new javax.swing.JLabel();
        PlayersSlider = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        RowsLabel = new javax.swing.JLabel();
        RowsSlider = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();
        ColumnsLabel = new javax.swing.JLabel();
        ColumnsSlider = new javax.swing.JSlider();
        jSeparator3 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(400, 400));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        PlayersLabel.setText("Players:");
        add(PlayersLabel);

        PlayersSlider.setMajorTickSpacing(1);
        PlayersSlider.setMaximum(8);
        PlayersSlider.setMinimum(2);
        PlayersSlider.setMinorTickSpacing(1);
        PlayersSlider.setPaintLabels(true);
        PlayersSlider.setPaintTicks(true);
        PlayersSlider.setSnapToTicks(true);
        PlayersSlider.setValue(2);
        add(PlayersSlider);
        add(jSeparator1);

        RowsLabel.setText("Rows:");
        add(RowsLabel);

        RowsSlider.setMajorTickSpacing(1);
        RowsSlider.setMaximum(10);
        RowsSlider.setMinimum(3);
        RowsSlider.setMinorTickSpacing(1);
        RowsSlider.setPaintLabels(true);
        RowsSlider.setPaintTicks(true);
        RowsSlider.setSnapToTicks(true);
        RowsSlider.setValue(9);
        add(RowsSlider);
        add(jSeparator2);

        ColumnsLabel.setText("Columns:");
        add(ColumnsLabel);

        ColumnsSlider.setMajorTickSpacing(1);
        ColumnsSlider.setMaximum(10);
        ColumnsSlider.setMinimum(3);
        ColumnsSlider.setMinorTickSpacing(1);
        ColumnsSlider.setPaintLabels(true);
        ColumnsSlider.setPaintTicks(true);
        ColumnsSlider.setSnapToTicks(true);
        ColumnsSlider.setValue(6);
        add(ColumnsSlider);
        add(jSeparator3);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColumnsLabel;
    private javax.swing.JSlider ColumnsSlider;
    private javax.swing.JLabel PlayersLabel;
    private javax.swing.JSlider PlayersSlider;
    private javax.swing.JLabel RowsLabel;
    private javax.swing.JSlider RowsSlider;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
