package Panel;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Josh
 */
public class GameManager extends JPanel {

    ArrayList<GamePanel> currentGames;

    /**
     * Creates a new Game manager. Has tabs with {@link GamePanel}s and setup panels.
     */
    public GameManager() {
        initComponents();
    }

    /**
     * Removes a tab in this manager.
     *
     * @param component The tab to remove.
     */
    public void removeTab(Component component) {
        jTabbedPane1.remove(jTabbedPane1.indexOfComponent(component));
    }

    /**
     * Adds a new {@link GamePanel} to this manager.
     *
     * @param game The GamePanel to add to this manager.
     */
    public void addGameTab(GamePanel game) {
        jTabbedPane1.add("Game", game);
    }

    /**
     * Adds a new tab to the manager.
     *
     * @param name The title of the added tab.
     * @param component The component to add.
     */
    public void addTab(String name, Component component) {
        jTabbedPane1.addTab(name, component);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        Component comp = evt.getComponent();
        if (comp instanceof GamePanel) {
            GamePanel game = (GamePanel) comp;
            game.startTimer();
        }
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        Component comp = evt.getComponent();
        if (comp instanceof GamePanel) {
            GamePanel game = (GamePanel) comp;
            game.stopTimer();
        }
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        Component comp = jTabbedPane1.getSelectedComponent();

        if (comp instanceof GamePanel) {

            GamePanel game = (GamePanel) comp;
            game.startTimer();

        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
