/*
 * Copyright (c) 2014, Deliquescence <Deliquescence1@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * - Neither the name of the copyright holder nor the names of its contributors
 *   may be used to endorse or promote products derived from this software
 *   without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package Deliquescence.Network;

import Deliquescence.Panel.GameManager;

/**
 *
 * @author Deliquescence <Deliquescence1@gmail.com>
 */
public class NetworkSetupPanel extends javax.swing.JPanel {

    GameManager gameManager;
    GameManager gameListPanel;

    /**
     * Creates new form NetworkSetupPanel
     */
    public NetworkSetupPanel(GameManager gameManager, GameManager gameList) {
        this.gameManager = gameManager;
        this.gameListPanel = gameList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        LeftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LocalPlayersSlider = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        gameSliders1 = new Deliquescence.Panel.GameSliders();
        StartButton = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        gameSettings1 = new Deliquescence.Panel.GameSettings();

        jButton1.setText("make server");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("make client");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("client send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("server send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setLabelFor(LocalPlayersSlider);
        jLabel1.setText("Number of players on this machine:");
        LeftPanel.add(jLabel1);

        LocalPlayersSlider.setMajorTickSpacing(1);
        LocalPlayersSlider.setMaximum(8);
        LocalPlayersSlider.setMinimum(1);
        LocalPlayersSlider.setMinorTickSpacing(1);
        LocalPlayersSlider.setPaintLabels(true);
        LocalPlayersSlider.setPaintTicks(true);
        LocalPlayersSlider.setSnapToTicks(true);
        LocalPlayersSlider.setValue(1);
        LeftPanel.add(LocalPlayersSlider);
        LeftPanel.add(jSeparator1);
        LeftPanel.add(gameSliders1);

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(StartButton);

        jSplitPane1.setLeftComponent(LeftPanel);

        RightPanel.setLayout(new java.awt.GridLayout(1, 0));
        RightPanel.add(gameSettings1);

        jSplitPane1.setRightComponent(RightPanel);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //createServer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //createClient();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*try {
         MyNetworkObject mno = new MyNetworkObject();
         mno.text = "Client send";
         client.sendTCP(mno);
         //System.out.println("attempted client send");
         } catch (Exception e) {
         System.err.println(e);
         }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*try {
         MyNetworkObject mno = new MyNetworkObject();
         mno.text = "Server send";
         server.sendToAllTCP(mno);
         //System.out.println("attempted server send");
         } catch (Exception e) {
         System.err.println(e);
         }*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        GameManager man = (GameManager) this.getParent().getParent();//Sketchy
        man.switchToTabByTitle("Games");

        NetworkGameSettings settings = new NetworkGameSettings();

        settings.RNGEnabled = gameSettings1.EnableRNGButton();
        settings.cols = gameSliders1.getColumns();
        settings.totalPlayers = gameSliders1.getPlayers();
        settings.randomStartingPlayer = gameSettings1.RandomStartPlayer();
        settings.rows = gameSliders1.getRows();

        //settings.timerAction = TOdO
        settings.timerLength = gameSettings1.TimerLength();
        settings.turnTimerEnabled = gameSettings1.EnableTurnTimer();

        gameListPanel.addTab("Hosted Game", new NetworkGameViewer(gameListPanel, settings, LocalPlayersSlider.getValue()), false, true);
    }//GEN-LAST:event_StartButtonActionPerformed

    /* private void createServer() {
     try {
     server = new Server();
     server.addListener(new ServerListener());
     server.start();

     server.bind(Config.getInt("NETWORK_PORT"));

     /*Kryo kryo = server.getKryo();
     kryo.register(MyNetworkObject.class);
     } catch (Exception e) {
     System.err.println(e);
     }
     }

     private void createClient() {
     try {
     client = new Client();
     client.addListener(new ClientListener());
     client.start();

     client.connect(5000, "localhost", Config.getInt("NETWORK_PORT"));

     /*Kryo kryo = client.getKryo();
     kryo.register(MyNetworkObject.class);
     } catch (Exception e) {
     System.err.println(e);
     }
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JSlider LocalPlayersSlider;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton StartButton;
    private Deliquescence.Panel.GameSettings gameSettings1;
    private Deliquescence.Panel.GameSliders gameSliders1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
